version: '3'

services:
  app:
    build: 
      context: ./bot_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
